export interface Resource {
	id?: number
	name: string
	country_code: string
	city: string
	state: string
	address?: string
	phone_number?: string
	date_added?: Date // auto-generated by db
	description: string
	href: string
}

export type ResourcesResponse = {
	resources: Resource[]
	total: number
	countries: string[]
	states: string[]
	cities: string[]
	limit: string
}
