FROM node:alpine

ENV PORT 3000

# where our Next.js app will live
RUN mkdir -p /app

# Set /app as the working directory
WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED 1

ENV NEXT_PUBLIC_ENVIRONMENT=development
ENV API_URL=https://devapi.ratethelandlord.org
ENV ORIGIN_URL=https://dev.ratethelandlord.org

# Copy package.json and package-lock.json
# to the /app working directory
COPY package*.json  /app/

# Install dependencies in /app
RUN npm ci

# Copy the rest of our Next.js folder into /app
COPY . /app

ENV NODE_ENV=development

# Build app
RUN npm run build

EXPOSE 3000

# Run npm dev, as we would via the command line
CMD [ "npm", "run", "start" ]