import { Options } from '@/util/interfaces/interfaces'

export interface Review {
	id?: number
	landlord: string
	country_code: string
	city: string
	state: string
	zip: string
	review: string
	repair: number
	health: number
	stability: number
	privacy: number
	respect: number
	date_added: Date // auto-generated by db
	flagged: boolean
	flagged_reason: string
	admin_approved: boolean | null
	admin_edited: boolean
	rent?: number | null
	moderation_reason: string | null
	moderator: Array<string> | null
	delete_date: string | null
	delete_reason: string | null
	deleted_by: Array<string> | null
	restore_date: string | null
	restore_reason: string | null
	restored_by: Array<string> | null
}

export interface OtherLandlord {
	name: string
	avgrating: number
	topcity: string
	reviewcount: number
}

export type ReviewsResponse = {
	reviews: Review[]
	total: number
	countries: string[]
	cities: string[]
	zips: string[]
	limit: number
}

export type FilterOptions = {
	countries: Options[]
	cities: Options[]
	zips: Options[]
}

export interface ReviewResponseStatus {
	success: boolean
	message: string
}
