import { runMiddleware } from '@/util/cors'
import { NextApiRequest, NextApiResponse } from 'next'
import { getSession, withApiAuthRequired } from '@auth0/nextjs-auth0'
import { update } from '@/lib/suspicious-landlords/suspicious-landlords'

interface IBody {
	id: number
	landlord: string
	message: string
	date_added?: Date // auto-generated by db
}

const EditSuspiciousLandlordAPI = async (
	req: NextApiRequest,
	res: NextApiResponse,
) => {
	const session = await getSession(req, res)
	const user = session?.user
	await runMiddleware(req, res)

	// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
	const { body }: { body: IBody } = req

	if (user && user.role === 'ADMIN' && user.admin_id === 'rtl-001') {
		const edit = await update(body.id, body)
		res.status(edit.status).json(edit.message)
	} else {
		res.status(401).json({ error: 'UNAUTHORIZED' })
	}
}

export default withApiAuthRequired(EditSuspiciousLandlordAPI)
