export interface Review {
	id?: number
	landlord: string
	country_code: string
	city: string
	state: string
	zip: string
	review: string
	repair: number
	health: number
	stability: number
	privacy: number
	respect: number
	date_added: Date // auto-generated by db
	flagged: boolean
	flagged_reason: string
	admin_approved: boolean | null
	admin_edited: boolean
	rent?: number | null
	moderation_reason: string | null
	moderator: Array<string> | null
	delete_date: string | null
	delete_reason: string | null
	deleted_by: Array<string> | null
	restore_date: string | null
	restore_reason: string | null
	restored_by: Array<string> | null
	user_code?: string
	number_user_attempts: number
	last_user_attempt: Date
}

export interface UserReview {
	id?: number
	landlord: string
	country_code: string
	city: string
	state: string
	zip: string
	review: string
	repair: number
	health: number
	stability: number
	privacy: number
	respect: number
	date_added: Date // auto-generated by db
	rent?: number | null
	moderation_reason: string | null
	has_user_code?: boolean
}

export interface OtherLandlord {
	name: string
	avgrating: number
	topCity: string
	reviewcount: number
}

export interface Options {
	id: number
	name: string
	value: string
}

export interface SortOptions {
	id: number
	name: string
	value: 'az' | 'za' | 'new' | 'old' | 'high' | 'low' | undefined
}

export interface ILinks {
	name: string
	href: string
	icon: JSX.Element
}

export interface INav {
	href: string
	name: string
}

export interface ILocationResponse {
	address: {
		['code']: string
		city: string
		country: string
		country_code: string
		county: string
		postcode: string
		state: string
		state_district: string
	}
	boundingbox: string[]
	class: string
	display_name: string
	icon: string
	importance: number
	lat: string
	licence: string
	lon: string
	osm_id: number
	osm_type: string
	place_id: number
	type: string
}

export interface ILocationHookResponse {
	id: number
	city: string
	state: string
}

export interface Resource {
	id: number
	name: string
	country_code: string
	city: string
	state: string
	address?: string
	phone_number?: string
	date_added: Date // auto-generated by db
	description: string
	href: string
}

export interface ResourceResponse {
	resources: Resource[]
	total: string
	countries: string[]
	states: string[]
	cities: string[]
	limit: number
}

export interface FilterOptions {
	countries: Options[]
	states: Options[]
	cities: Options[]
	zips: Options[]
}

export interface ReviewResponseStatus {
	success: boolean
	message: string
}

export interface SuspiciousLandlord {
	id?: number
	landlord: string
	message: string
	date_added?: Date
}

export interface SuspiciousLandlordResponse {
	landlords: SuspiciousLandlord[]
	total: string
	limit: number
}

export interface Keywords {
	id?: number
	keyword: string
	reason: string
	date_added?: Date
}

export interface FlaggedKeywordsResponse {
	keywords: Keywords[]
	total: string
	limit: number
}

export interface IQuery {
	selectedSort: SortOptions
	countryFilter: Options | null
	stateFilter: Options | null
	cityFilter: Options | null
	zipFilter: Options | null
	activeFilters: (Options | null)[] | null
	searchFilter: string | undefined
}

export interface AnalyticsResponseInterface {
	review_date: string
	metric: number
}

export interface RecentReviews {
	id: number
	landlord: string
	created_at: string
}

export interface UserUpdatedReview {
	landlord: string
	review: string
	repair: number
	health: number
	stability: number
	respect: number
	privacy: number
	rent: number | null
}
