import { update } from '@/lib/tenant-resource/resource'
import { runMiddleware } from '@/util/cors'
import { NextApiRequest, NextApiResponse } from 'next'
import { getSession, withApiAuthRequired } from '@auth0/nextjs-auth0'

interface IBody {
	id: number
	name: string
	country_code: string
	city: string
	state: string
	address?: string
	phone_number?: string
	date_added?: Date // auto-generated by db
	description: string
	href: string
}

const EditResourceAPI = async (req: NextApiRequest, res: NextApiResponse) => {
	const session = await getSession(req, res)
	const user = session?.user
	await runMiddleware(req, res)

	// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
	const { body }: { body: IBody } = req

	if (user && user.role === 'ADMIN') {
		const edit = await update(body.id, body)
		res.status(edit.status).json(edit.message)
	} else {
		res.status(401).json({ error: 'UNAUTHORIZED' })
	}
}

export default withApiAuthRequired(EditResourceAPI)
