name: Deploy production

on:
  push:
    branches: [production]

jobs:
  deploy-fe:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to Digital Ocean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_FRONTEND }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 200m
          script_stop: true
          script: |
            cd rtl-frontend
            git pull
            bun install
            bun run build
            bun run start:infisical
            pm2 list
