name: Build Production Image

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ vars.ENVIRONMENT_PRODUCTION }}

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      # Build and push
      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/rtl-application:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/rtl-application:latest
          build-args: |
            NEXT_PUBLIC_CAPTCHA_SITE_KEY=${{ vars.NEXT_PUBLIC_CAPTCHA_SITE_KEY }}
            NEXT_PUBLIC_ENVIRONMENT=${{ vars.NEXT_PUBLIC_ENVIRONMENT }}
            NEXT_PUBLIC_GMAPS_TOKEN=${{ vars.NEXT_PUBLIC_GMAPS_TOKEN }}
            NEXT_PUBLIC_MAPBOX_TOKEN=${{ vars.NEXT_PUBLIC_MAPBOX_TOKEN }}
            NEXT_PUBLIC_ORIGIN_URL=${{ vars.NEXT_PUBLIC_ORIGIN_URL }}
            NEXT_PUBLIC_POSTHOG_HOST=${{ vars.NEXT_PUBLIC_POSTHOG_HOST }}
            NEXT_PUBLIC_POSTHOG_KEY=${{ vars.NEXT_PUBLIC_POSTHOG_KEY }}
