name: Merge Develop Actions

on:
  pull_request:
    branches: ['develop']

jobs:
  lint-fe:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint Frontend
      run: |
        curl -fsSL https://bun.sh/install | bash
        export PATH=$HOME/.bun/bin:$PATH
        bun --version
        bun install
        bun run lint

  test-fe:
    runs-on: ubuntu-latest
    needs: [lint-fe]

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test Frontend
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH=$HOME/.bun/bin:$PATH
          bun --version
          bun install
          bun run test:merge
