name: Merge Main Actions

on:
  pull_request:
    branches: ['production']

jobs:
  lint-fe:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint frontend
        run: |
          npm install
          npm run lint

  test-fe:
    runs-on: ubuntu-latest
    needs: [lint-fe]

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test frontend
        run: |
          npm install
          npm run test:merge

  deploy-fe:
    runs-on: ubuntu-latest
    needs: [lint-fe, test-fe]

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to Digital Ocean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_FRONTEND }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 200m
          script_stop: true
          script: |
            cd rtl-frontend
            git pull
            bun install
            bun run build
            bun run start:infisical
            pm2 list
